DATA_PATH = "/data"
IMAGE_PATH = "/image"
UNKNOWN_FILE_PATH = "./modules/unknown.png"
SAVE_FILE = "/save.tsv"
ICON_FILE = "./icon.png"

DEFAULT_SCORE = 0
DEFAULT_DOUBT = 400
MINIMUM_DOUBT = 30
SURPRISE_FACTOR = (DEFAULT_DOUBT**2 - MINIMUM_DOUBT**2)/5

STANDARD_GAP = 400
EXPECTANCY_BASE = 9